"""``cliyard gen`` — Generate a standalone CLI tool from YAML specs.

Usage::

    cliyard gen --name ketacliv2 --defs-path tests/fixtures/spec-dir/
    cd dist/ketacliv2 && pip install -e .
    ketacliv2 repos list --help
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import yaml  # noqa: F401 — used in gen() for parsing resource YAMLs

import click

_PYPROJECT_TOML_TEMPLATE = """\
[project]
name = "{CLI_NAME}"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["cliyard>=0.1.0"]

[project.scripts]
{CLI_NAME} = "{pkg_name}.main:main"

[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"{pkg_name}" = ["specs/*.yaml", "specs/resources/*.yaml", "specs/flows/*.yaml", "specs/plugins/*.py", "specs/plugins/spl_parser/*.py"]
"""

_MAIN_PY_TEMPLATE = """\
\"\"\"CLI entry point. Edit this file to customize commands.\"\"\"
import sys
from pathlib import Path
try:
    from importlib.metadata import version, PackageNotFoundError
    _VER = version("{pkg_name}")
except PackageNotFoundError:
    _VER = "0.0.0"
from click.exceptions import UsageError
from cliyard.runtime import create_cli
from cliyard.runtime.runner import extract_server_override

_SPEC_DIR = Path(__file__).parent / "specs"


def main():
    try:
        argv, server = extract_server_override(sys.argv[1:])
        if argv != sys.argv[1:]:
            sys.argv = [sys.argv[0]] + argv
        cli = create_cli(str(_SPEC_DIR), version=_VER, base_url_override=server)
        sys.exit(cli(standalone_mode=False))
    except UsageError as e:
        sys.exit(e.format_message())
"""
_INIT_PY = ""

_README_TEMPLATE = """\
# {CLI_NAME}

Generated by [cliyard](https://github.com/example/cliyard).

## Install

```bash
pip install -e .
```

## Usage

```bash
# Show available commands
{CLI_NAME} --help

# Authenticate (first time)
{CLI_NAME} auth add -n myenv -e <endpoint> -u <user> -p <pass>

# Or use an existing token
{CLI_NAME} auth add -n myenv -e <endpoint> -t <token>

# Run commands
{CLI_NAME} <resource> list --page-size 10
{CLI_NAME} <resource> list --format json
```

## Directory structure

```
src/{pkg_name}/specs/
├── _auth.yaml              # Service config (server, auth)
├── _groups.yaml            # (optional) Group definitions
├── _flows.yaml             # (optional) Flow orchestration index
├── resources/              # Resource YAML files
│   ├── repos.yaml
│   └── ...
├── flows/                  # (optional) Flow step definitions
│   ├── _flow_create_repo.yaml
│   └── ...
└── plugins/                # Python plugins
    └── *.py
```

## Adding new resources

1. Create a YAML file in `src/{pkg_name}/specs/resources/` (or directly in `specs/`):

```yaml
description: My resource
path: myresource
methods:
  list:
    http:
      method: GET
    output:
      items_path: $.items
      fields:
        - name: id
          alias: ID
  create:
    http:
      method: POST
    params:
      body:
        - name: name
          type: string
          required: true
```

2. Re-run `cliyard gen --name {CLI_NAME}` in the project directory to regenerate the CLI.

## Customizing commands

To add custom logic or new commands, use the plugin system instead of editing ``main.py``:

```python
# src/{pkg_name}/specs/plugins/my_custom.py
from cliyard.plugin import register_command

@register_command("mycmd")
def register_mycmd(cli, ctx):
    @click.command("mycmd")
    @click.argument("input")
    def mycmd(input):
        click.echo(f"Input: {input}")
    cli.add_command(mycmd)
```

See the **Top-level command plugins** section below for details.

## Adding plugins

Create a `.py` file in `src/{pkg_name}/specs/plugins/`:

```python
from cliyard.plugin import register_auth_step, register_hook

@register_auth_step("custom_login")
class CustomLogin:
    def execute(self, auth_state, config, http_client):
        # Custom auth logic
        token = "my-token"
        http_client.default_headers["Authorization"] = f"Bearer {token}"
        auth_state["token"] = token
        return token

@register_hook("custom_hook")
def custom_hook(req):
    req.headers["X-Custom"] = "value"
    return req
```

Reference plugins in `_auth.yaml`:

```yaml
auth:
  steps:
    - name: login
      type: plugin:custom_login
```

## Custom method plugins

For business logic that involves multiple API calls, write a method plugin:

```python
# src/{pkg_name}/specs/plugins/my_biz.py
from cliyard.plugin import register_method

@register_method("multi_step_import")
def multi_step_import(params, http_client, config):
    # Step 1: prepare
    r1 = http_client.request("POST", "/api/prepare", data=params)
    # Step 2: transform and commit
    r2 = http_client.request("POST", "/api/commit", json=r1.json())
    return {"status": "done", "id": r2.json().get("id")}
```

Reference it in a resource YAML:

```yaml
methods:
  import:
    type: plugin:multi_step_import
    config:
      batch_size: 100
    params:
      body:
        - name: source
          type: string
          required: true
```

The plugin function receives ``params`` (validated CLI args), ``http_client``
(authenticated), and ``config`` (from YAML). The return value is JSON output.

## Top-level command plugins

For standalone commands that don't belong to any resource group (e.g. ``search``,
``mock``, ``insert``), use ``@register_command``:

```python
# src/{pkg_name}/specs/plugins/mycmd.py
import click
from cliyard.plugin import register_command

@register_command("mycmd")
def register_mycmd(cli, ctx):
    @click.command("mycmd")
    @click.argument("input")
    @click.option("--verbose", is_flag=True)
    def mycmd(input, verbose):
        \"\"\"My custom top-level command.\"\"\"
        click.echo(f"Input: {input}")

    cli.add_command(mycmd)
```

The function receives the top-level ``cli`` (``click.Group``) and ``ctx``
(``ServiceContext`` containing base_url, auth config, etc.). Call
``cli.add_command(...)`` with your built Click command.

### Available plugin decorators

| Decorator | Purpose |
|-----------|---------|
| ``@register_step_type("name")`` | **Custom flow orchestration step** (referenced in ``_flows.yaml`` via ``type: plugin:xxx``) |
| ``@register_auth_step("name")`` | Custom authentication step (referenced in ``_auth.yaml``) |
| ``@register_field_type("name")`` | Custom field type validator |
| ``@register_hook("name")`` | Pre/post request hook |
| ``@register_method("name")`` | Multi-step business method (referenced in YAML via ``type: plugin:xxx``) |
| ``@register_command("name")`` | **Top-level Click command** (not tied to any resource) |
| ``@register_field_resolver("name")`` | Dynamic field value resolver (e.g. auto-fill version) |

## Flow orchestration（命令编排）

对于涉及多个 API 调用的业务流程，可以通过 ``_flows.yaml`` 定义编排流水线。
编排定义分为两层：

* **注册索引** ``flows/_flows.yaml`` — 定义命令名、参数、引用步骤文件
* **步骤文件** ``flows/_flow_<name>.yaml`` — 存放具体步骤逻辑

### 快速开始

创建 ``src/{pkg_name}/specs/flows/_flows.yaml``：

```yaml
flows:
  add_user:
    description: 新增用户流程
    command: add-user
    steps: _flow_add_user.yaml       # 引用步骤文件
    params:
      query:
        - name: name
          type: string
          required: true
          description: 用户名
        - name: phone
          type: string
          description: 手机号
```

再创建 ``src/{pkg_name}/specs/flows/_flow_add_user.yaml``：

```yaml
steps:
  - id: check_user
    description: 查询用户是否存在
    use: user.list
    params:
      name: '{{ flow.name }}'
    extract:
      exists: $.users | length

  - id: decision
    on_result:
      - if: '{{ step.check_user.exists > 0 }}'
        then:
          - type: echo
            message: "用户 {{ flow.name }} 已存在"
          - action: return
      - else:
          steps:
            - id: create_user
              use: user.create
              params:
                name: '{{ flow.name }}'
                phone: '{{ flow.phone | default("") }}'
```

使用方式：

```bash
{CLI_NAME} flow run add-user --help
{CLI_NAME} flow run add-user --name 张三 --phone 13800138000
```

也可将所有步骤直接写在 ``_flows.yaml`` 的 ``steps:`` 字段中（适用于简单流程）。

### 步骤引用（include）

步骤列表支持 Ansible-playbook 风格的 ``include:``，可组合多个文件：

```yaml
# flows/_flows.yaml
flows:
  deploy:
    command: deploy
    steps: _flow_deploy.yaml

# flows/_flow_deploy.yaml
steps:
  - include: _flow_common_check.yaml    # 引入通用检查步骤
  - id: do_deploy
    use: app.deploy
  - include: _flow_common_verify.yaml   # 引入通用验证步骤
```

### 核心概念

| 概念 | 说明 |
|------|------|
| ``use: resource.method`` | 引用已有 CLI 命令（如 ``user.list``、``repos.create``） |
| ``{{ flow.xxx }}`` | 引用 flow 级 CLI 参数 |
| ``{{ step.<id>.xxx }}`` | 引用前序步骤的输出 |
| ``on_result`` + ``if/else`` | 基于步骤结果的条件分支 |
| ``for_each`` | 遍历列表，对每项执行子步骤 |
| ``retry`` | 失败后自动重试，支持指数退避 |
| ``until`` | 轮询等待直到条件满足 |

### 条件分支

```yaml
on_result:
  - if: '{{ step.check.count > 0 }}'
    then:
      - type: echo
        message: "条件满足"
      - action: return      # 正常退出
  - else:
      steps:
        - id: do_something
          use: resource.method
```

内置动作：``return``（退出）、``abort``（中止）、``warn``（警告）、``skip``（跳过）。

### 循环

```yaml
# 遍历（for_each）
- id: batch_process
  for_each:
    items: '{{ step.list.items }}'
    as: item
    steps:
      - id: process
        use: resource.method
        params:
          body:
            name: '{{ item.name }}'

# 重试（retry）
- id: deploy
  use: resource.method
  retry:
    max_attempts: 3
    delay: 2
    backoff: 2              # 指数退避：2s → 4s → 8s
    on_exhausted:
      action: abort

# 轮询（until）
- id: wait_ready
  use: resource.get
  until:
    max_iterations: 30
    interval: 5
    condition: '{{ step.wait_ready.status == "RUNNING" }}'
    timeout_action: abort
```

### 插件步骤

对于 ``use:`` 无法覆盖的逻辑（如发送通知、数据转换），可以注册自定义步骤：

```python
# src/{pkg_name}/specs/plugins/my_steps.py
from cliyard.plugin import register_step_type

@register_step_type("send_notification")
def send_notification(params, context):
    console = context["console"]
    console.print(f"[blue]通知: {params['message']}[/blue]")
    return {"sent": True}
```

在 ``_flows.yaml`` 中引用：

```yaml
- id: notify
  type: plugin:send_notification
  params:
    message: "处理完成"
```

### 钩子（Hook）

```yaml
# flows/_flows.yaml
flows:
  deploy_app:
    hooks:
      on_start: [validate_env]       # 流程启动时
      on_end: [notify_result]         # 流程完成时
      on_failure: [notify_failure]    # 流程失败时
    steps: _flow_deploy.yaml

## Multiple environments

```bash
# Add environments
{CLI_NAME} auth add -n dev -e https://dev.example.com -t <token>
{CLI_NAME} auth add -n prod -e https://prod.example.com -t <token> --default

# Switch between them
{CLI_NAME} auth switch prod
{CLI_NAME} --env prod <resource> list
```

## Multi-server configuration

When an API is composed of multiple services at different endpoints,
declare them in ``_auth.yaml`` without hardcoding ``base_url``:

```yaml
server:
  - name: serve4go
    prefix: /api/v1
  - name: serve4java
    prefix: /api/v2
```

The ``name`` fields dynamically generate ``--server-<name>`` options on
``auth add``. Endpoints are provided at authentication time:

```bash
# Multi-server: one URL per server
{CLI_NAME} auth add -n prod \\
  --server-serve4go https://go-api.example.com \\
  --server-serve4java https://java-api.example.com

# Single server: use -e as fallback
{CLI_NAME} auth add -n prod -e https://api.example.com
```

Resources select their server via the ``server:`` field:

```yaml
# repos.yaml — uses the default (first) server
description: 仓库管理
path: repos

# alerts.yaml — uses the "serve4java" server
server: serve4java
description: 告警规则
path: alerts
```

If a resource does not specify ``server:``, it uses the first server
in the list. Auth steps can also specify a ``server:`` field to
choose which endpoint to authenticate against.
"""


@click.command()
@click.option("--name", required=True, help="Name of the generated CLI tool")
@click.option(
    "--defs-path",
    default=None,
    type=click.Path(exists=True, file_okay=False, resolve_path=True),
    help="Path to YAML spec directory (omit for empty scaffold)",
)
@click.option(
    "--output",
    default=None,
    type=click.Path(file_okay=False, resolve_path=True),
    help="Output directory (default: ./<name>/)",
)
def gen(name: str, defs_path: str | None, output: str | None) -> None:
    """Generate a standalone CLI tool from YAML specs.

    Reads a cliyard service spec directory (containing ``_auth.yaml``
    and resource YAML files) and produces a pip-installable Python package
    in the output directory. If ``--defs-path`` is omitted, generates an
    empty scaffold that you can fill in later.
    """
    pkg_name = name.replace("-", "_")
    output_dir = Path(output) if output else Path.cwd() / name
    output_dir = output_dir.resolve()

    # Create output structure
    src_dir = output_dir / "src" / pkg_name
    specs_dir = src_dir / "specs"
    specs_dir.mkdir(parents=True, exist_ok=True)

    click.echo(f"✔ Created output directory: {output_dir}")

    # 1. Validate or create defs-path
    if defs_path:
        spec_dir = Path(defs_path).resolve()
        service_yaml = spec_dir / "_auth.yaml"
        if not service_yaml.exists():
            click.echo(f"Error: {spec_dir} does not contain _auth.yaml", err=True)
            sys.exit(1)
        click.echo(f"✔ Found _auth.yaml in {spec_dir}")
    else:
        # No --defs-path: check if output specs/ already has YAMLs
        existing_svc = specs_dir / "_auth.yaml"
        if existing_svc.exists():
            spec_dir = specs_dir  # Regenerate from existing specs
            click.echo(f"✔ Reusing specs from {specs_dir}")
        else:
            spec_dir = None
            # Generate a minimal _auth.yaml for the scaffold
            scaffold_svc = specs_dir / "_auth.yaml"
            scaffold_svc.write_text(f"""\
name: {name}
version: "0.1.0"
description: CLI for {name}
server:
  base_url: http://localhost:8080
""")
            click.echo("✔ Generated empty scaffold (add YAMLs to src/{pkg_name}/specs/)")

    # 2. Generate pyproject.toml

    # 3. Generate pyproject.toml
    pyproject_path = output_dir / "pyproject.toml"
    pyproject_path.write_text(
        _PYPROJECT_TOML_TEMPLATE
        .replace("{CLI_NAME}", name)
        .replace("{pkg_name}", pkg_name)
    )
    click.echo(f"✔ Generated pyproject.toml")

    # 4. Generate src/<pkg_name>/__init__.py
    init_path = src_dir / "__init__.py"
    init_path.write_text(_INIT_PY)
    click.echo(f"✔ Generated src/{pkg_name}/__init__.py")

    # 5. Generate src/<pkg_name>/main.py (thin wrapper around create_cli)
    main_path = src_dir / "main.py"
    main_path.write_text(_MAIN_PY_TEMPLATE.format(pkg_name=pkg_name))
    click.echo(f"✔ Generated src/{pkg_name}/main.py")

    # 6. Copy spec files (skip if already in specs_dir)
    copied = 0
    if spec_dir and spec_dir.resolve() != specs_dir.resolve():
        for yaml_file in sorted(spec_dir.glob("*.yaml")):
            dest = specs_dir / yaml_file.name
            shutil.copy2(yaml_file, dest)
            copied += 1
    elif spec_dir and spec_dir.resolve() == specs_dir.resolve():
        copied = len(list(spec_dir.glob("*.yaml")))  # Already in place
    click.echo(f"✔ Copied {copied} spec file(s) to src/{pkg_name}/specs/")

    # 6b. Copy plugins directory if it exists
    if spec_dir:
        plugins_src = spec_dir / "plugins"
        if plugins_src.is_dir():
            plugins_dest = specs_dir / "plugins"
            shutil.copytree(plugins_src, plugins_dest, dirs_exist_ok=True)
            click.echo(f"✔ Copied plugins/ to src/{pkg_name}/specs/plugins/")

    # 7. Generate README.md
    readme_path = output_dir / "README.md"
    readme_path.write_text(
        _README_TEMPLATE
        .replace("{CLI_NAME}", name)
        .replace("{pkg_name}", pkg_name)
    )
    click.echo(f"✔ Generated README.md")

    click.echo()
    click.echo(f"Package generated at {output_dir}")
    click.echo(f"To install:  cd {output_dir} && pip install -e .")
    click.echo(f"To use:      {name} --help")
